import flask
import pickle
import pandas as pd
import gzip
from sklearn.preprocessing import OrdinalEncoder
import joblib
v = {583: 'NONE,No Interactions Found',
 0: 'MAJOR,The metabolism of Acetaminophen can be decreased when combined with Ciprofloxacin.',
 29: 'MINOR,Acetaminophen may decrease the excretion rate of Amoxicillin which could result in a higher serum level.',
 298: 'MODERATE,The metabolism of Atorvastatin can be decreased when combined with Acetaminophen.',
 292: 'MODERATE,The metabolism of Amlodipine can be increased when combined with Acetaminophen.',
 31: 'MINOR,Acetaminophen may decrease the excretion rate of Levofloxacin which could result in a higher serum level.',
 114: 'MINOR,Pantoprazole may decrease the excretion rate of Acetaminophen which could result in a higher serum level.',
 283: 'MODERATE,The metabolism of Acetaminophen can be decreased when combined with Metoprolol.',
 317: 'MODERATE,The metabolism of Clopidogrel can be decreased when combined with Acetaminophen.',
 222: 'MODERATE,Hydrochlorothiazide may increase the excretion rate of Acetaminophen which could result in a lower serum level and potentially a reduction in efficacy.',
 137: 'MINOR,The metabolism of Acetaminophen can be decreased when combined with Sertraline.',
 515: 'MODERATE,The serum concentration of Acetaminophen can be increased when it is combined with Escitalopram.',
 240: 'MODERATE,Ibuprofen may decrease the antiplatelet activities of Acetylsalicylic acid.',
 476: 'MODERATE,The risk or severity of hypoglycemia can be increased when Acetylsalicylic acid is combined with Metformin.',
 45: 'MINOR,Acetylsalicylic acid may increase the neuroexcitatory activities of Ciprofloxacin.',
 36: 'MINOR,Acetylsalicylic acid may decrease the excretion rate of Amoxicillin which could result in a higher serum level.',
 499: 'MODERATE,The risk or severity of renal failure, hyperkalemia, and hypertension can be increased when Losartan is combined with Acetylsalicylic acid.',
 285: 'MODERATE,The metabolism of Acetylsalicylic acid can be decreased when combined with Amlodipine.',
 46: 'MINOR,Acetylsalicylic acid may increase the neuroexcitatory activities of Levofloxacin.',
 41: 'MINOR,Acetylsalicylic acid may decrease the excretion rate of Pantoprazole which could result in a higher serum level.',
 200: 'MODERATE,Acetylsalicylic acid may decrease the antihypertensive activities of Metoprolol.',
 201: 'MODERATE,Acetylsalicylic acid may decrease the excretion rate of Hydrochlorothiazide which could result in a higher serum level.',
 44: 'MINOR,Acetylsalicylic acid may decrease the excretion rate of Tramadol which could result in a higher serum level.',
 459: 'MODERATE,The risk or severity of bleeding can be increased when Sertraline is combined with Acetylsalicylic acid.',
 466: 'MODERATE,The risk or severity of gastrointestinal bleeding can be increased when Escitalopram is combined with Acetylsalicylic acid.',
 467: 'MODERATE,The risk or severity of gastrointestinal bleeding can be increased when Fluoxetine is combined with Acetylsalicylic acid.',
 76: 'MINOR,Ibuprofen may decrease the excretion rate of Metformin which could result in a higher serum level.',
 343: 'MODERATE,The metabolism of Ibuprofen can be decreased when combined with Ciprofloxacin.',
 71: 'MINOR,Ibuprofen may decrease the excretion rate of Amoxicillin which could result in a higher serum level.',
 349: 'MODERATE,The metabolism of Ibuprofen can be decreased when combined with Omeprazole.',
 305: 'MODERATE,The metabolism of Atorvastatin can be decreased when combined with Ibuprofen.\n\n',
 500: 'MODERATE,The risk or severity of renal failure, hyperkalemia, and hypertension can be increased when Losartan is combined with Ibuprofen.',
 342: 'MODERATE,The metabolism of Ibuprofen can be decreased when combined with Amlodipine.',
 82: 'MINOR,Ibuprofen may increase the neuroexcitatory activities of Levofloxacin.',
 77: 'MINOR,Ibuprofen may decrease the excretion rate of Pantoprazole which could result in a higher serum level.',
 238: 'MODERATE,Ibuprofen may decrease the antihypertensive activities of Metoprolol.',
 454: 'MODERATE,The risk or severity of bleeding can be increased when Ibuprofen is combined with Clopidogrel.',
 274: 'MODERATE,The excretion of Hydrochlorothiazide can be decreased when combined with Ibuprofen.',
 80: 'MINOR,Ibuprofen may decrease the excretion rate of Tramadol which could result in a higher serum level.',
 456: 'MODERATE,The risk or severity of bleeding can be increased when Ibuprofen is combined with Sertraline.\n\n',
 162: 'MINOR,The risk or severity of gastrointestinal bleeding can be increased when Escitalopram is combined with Ibuprofen.\n\n',
 164: 'MINOR,The risk or severity of gastrointestinal bleeding can be increased when Fluoxetine is combined with Ibuprofen.',
 559: 'MODERATE,The therapeutic efficacy of Acetylsalicylic acid can be decreased when used in combination with Naproxen.',
 442: 'MODERATE,The risk or severity of adverse effects can be increased when Naproxen is combined with Ibuprofen.',
 108: 'MINOR,Naproxen may decrease the excretion rate of Metformin which could result in a higher serum level.',
 8: 'MAJOR,The metabolism of Naproxen can be decreased when combined with Ciprofloxacin.',
 107: 'MINOR,Naproxen may decrease the excretion rate of Amoxicillin which could result in a higher serum level.',
 252: 'MODERATE,Naproxen may decrease the excretion rate of Atorvastatin which could result in a higher serum level.',
 501: 'MODERATE,The risk or severity of renal failure, hyperkalemia, and hypertension can be increased when Losartan is combined with Naproxen.',
 356: 'MODERATE,The metabolism of Naproxen can be decreased when combined with Amlodipine.',
 111: 'MINOR,Naproxen may increase the neuroexcitatory activities of Levofloxacin.',
 109: 'MINOR,Naproxen may decrease the excretion rate of Pantoprazole which could result in a higher serum level.',
 251: 'MODERATE,Naproxen may decrease the antihypertensive activities of Metoprolol.',
 457: 'MODERATE,The risk or severity of bleeding can be increased when Naproxen is combined with Clopidogrel.',
 574: 'MODERATE,The therapeutic efficacy of Naproxen can be decreased when used in combination with Hydrochlorothiazide.',
 110: 'MINOR,Naproxen may decrease the excretion rate of Tramadol which could result in a higher serum level.',
 458: 'MODERATE,The risk or severity of bleeding can be increased when Naproxen is combined with Sertraline.',
 163: 'MINOR,The risk or severity of gastrointestinal bleeding can be increased when Escitalopram is combined with Naproxen.',
 165: 'MINOR,The risk or severity of gastrointestinal bleeding can be increased when Fluoxetine is combined with Naproxen.',
 215: 'MODERATE,Diazepam may increase the hepatotoxic activities of Acetaminophen.',
 37: 'MINOR,Acetylsalicylic acid may decrease the excretion rate of Diazepam which could result in a higher serum level.',
 73: 'MINOR,Ibuprofen may decrease the excretion rate of Diazepam which could result in a higher serum level.',
 92: 'MINOR,Metformin may decrease the excretion rate of Diazepam which could result in a higher serum level.',
 325: 'MODERATE,The metabolism of Diazepam can be decreased when combined with Ciprofloxacin.',
 60: 'MINOR,Diazepam may decrease the excretion rate of Amoxicillin which could result in a higher serum level.',
 328: 'MODERATE,The metabolism of Diazepam can be decreased when combined with Omeprazole.',
 301: 'MODERATE,The metabolism of Atorvastatin can be decreased when combined with Diazepam',
 327: 'MODERATE,The metabolism of Diazepam can be decreased when combined with Losartan.',
 324: 'MODERATE,The metabolism of Diazepam can be decreased when combined with Amlodipine.',
 61: 'MINOR,Diazepam may decrease the excretion rate of Levofloxacin which could result in a higher serum level.',
 329: 'MODERATE,The metabolism of Diazepam can be decreased when combined with Pantoprazole.',
 101: 'MINOR,Metoprolol may decrease the excretion rate of Diazepam which could result in a higher serum level.',
 326: 'MODERATE,The metabolism of Diazepam can be decreased when combined with Clopidogrel.',
 227: 'MODERATE,Hydrochlorothiazide may increase the excretion rate of Diazepam which could result in a lower serum level and potentially a reduction in efficacy.',
 387: 'MODERATE,The metabolism of Tramadol can be decreased when combined with Diazepam',
 433: 'MODERATE,The risk or severity of adverse effects can be increased when Diazepam is combined with Gabapentin.',
 434: 'MODERATE,The risk or severity of adverse effects can be increased when Diazepam is combined with Sertraline.',
 432: 'MODERATE,The risk or severity of adverse effects can be increased when Diazepam is combined with Escitalopram.',
 173: 'MINOR,The serum concentration of Diazepam can be increased when it is combined with Fluoxetine.',
 85: 'MINOR,Lorazepam may decrease the excretion rate of Acetaminophen which could result in a higher serum level.',
 40: 'MINOR,Acetylsalicylic acid may decrease the excretion rate of Lorazepam which could result in a higher serum level.',
 75: 'MINOR,Ibuprofen may decrease the excretion rate of Lorazepam which could result in a higher serum level.',
 88: 'MINOR,Lorazepam may decrease the excretion rate of Metformin which could result in a higher serum level.',
 353: 'MODERATE,The metabolism of Lorazepam can be decreased when combined with Ciprofloxacin.',
 86: 'MINOR,Lorazepam may decrease the excretion rate of Amoxicillin which could result in a higher serum level.',
 87: 'MINOR,Lorazepam may decrease the excretion rate of Levofloxacin which could result in a higher serum level.',
 89: 'MINOR,Lorazepam may decrease the excretion rate of Pantoprazole which could result in a higher serum level.',
 231: 'MODERATE,Hydrochlorothiazide may increase the excretion rate of Lorazepam which could result in a lower serum level and potentially a reduction in efficacy.',
 408: 'MODERATE,The risk or severity of CNS depression can be increased when Lorazepam is combined with Tramadol.',
 440: 'MODERATE,The risk or severity of adverse effects can be increased when Lorazepam is combined with Gabapentin.',
 441: 'MODERATE,The risk or severity of adverse effects can be increased when Lorazepam is combined with Sertraline.',
 439: 'MODERATE,The risk or severity of adverse effects can be increased when Lorazepam is combined with Escitalopram.',
 537: 'MODERATE,The serum concentration of Lorazepam can be increased when it is combined with Fluoxetine.',
 288: 'MODERATE,The metabolism of Alprazolam can be decreased when combined with Acetaminophen.',
 35: 'MINOR,Acetylsalicylic acid may decrease the excretion rate of Alprazolam which could result in a higher serum level.',
 70: 'MINOR,Ibuprofen may decrease the excretion rate of Alprazolam which could result in a higher serum level.',
 90: 'MINOR,Metformin may decrease the excretion rate of Alprazolam which could result in a higher serum level.',
 289: 'MODERATE,The metabolism of Alprazolam can be decreased when combined with Ciprofloxacin.',
 47: 'MINOR,Alprazolam may decrease the excretion rate of Amoxicillin which could result in a higher serum level.',
 142: 'MINOR,The metabolism of Atorvastatin can be decreased when combined with Alprazolam.',
 290: 'MODERATE,The metabolism of Alprazolam can be decreased when combined with Losartan.',
 48: 'MINOR,Alprazolam may decrease the excretion rate of Levofloxacin which could result in a higher serum level.',
 115: 'MINOR,Pantoprazole may decrease the excretion rate of Alprazolam which could result in a higher serum level.',
 405: 'MODERATE,The risk or severity of CNS depression can be increased when Alprazolam is combined with Tramadol.',
 147: 'MINOR,The metabolism of Clopidogrel can be decreased when combined with Alprazolam.',
 223: 'MODERATE,Hydrochlorothiazide may increase the excretion rate of Alprazolam which could result in a lower serum level and potentially a reduction in efficacy.',
 428: 'MODERATE,The risk or severity of adverse effects can be increased when Alprazolam is combined with Gabapentin.',
 429: 'MODERATE,The risk or severity of adverse effects can be increased when Alprazolam is combined with Sertraline.',
 517: 'MODERATE,The serum concentration of Alprazolam can be increased when it is combined with Fluoxetine.',
 455: 'MODERATE,The risk or severity of bleeding can be increased when Ibuprofen is combined with Sertraline.',
 481: 'MODERATE,The risk or severity of hypoglycemia can be increased when Sertraline is combined with Metformin.',
 372: 'MODERATE,The metabolism of Sertraline can be decreased when combined with Ciprofloxacin.',
 378: 'MODERATE,The metabolism of Sertraline can be decreased when combined with Omeprazole.',
 375: 'MODERATE,The metabolism of Sertraline can be decreased when combined with Losartan.',
 371: 'MODERATE,The metabolism of Sertraline can be decreased when combined with Amlodipine.',
 380: 'MODERATE,The metabolism of Sertraline can be decreased when combined with Pantoprazone',
 376: 'MODERATE,The metabolism of Sertraline can be decreased when combined with Metoprolol.',
 582: 'MODERATE,he serum concentration of the active metabolites of Clopidogrel can be reduced when Clopidogrel is used in combination with Sertraline resulting in a loss in efficacy.',
 485: 'MODERATE,The risk or severity of hyponatremia can be increased when Sertraline is combined with Hydrochlorothiazide.',
 512: 'MODERATE,The risk or severity of serotonin syndrome can be increased when Sertraline is combined with Tramadol.',
 437: 'MODERATE,The risk or severity of adverse effects can be increased when Gabapentin is combined with Sertraline.',
 511: 'MODERATE,The risk or severity of serotonin syndrome can be increased when Sertraline is combined with Escitalopram.',
 516: 'MODERATE,The serum concentration of Acetaminophen can be increased when it is combined with Fluoxetine.',
 480: 'MODERATE,The risk or severity of hypoglycemia can be increased when Fluoxetine is combined with Metformin.',
 413: 'MODERATE,The risk or severity of QTc prolongation can be increased when Fluoxetine is combined with Ciprofloxacin.',
 9: 'MAJOR,The metabolism of Omeprazole can be decreased when combined with Fluoxetine',
 417: 'MODERATE,The risk or severity of QTc prolongation can be increased when Fluoxetine is combined with Losartan.',
 341: 'MODERATE,The metabolism of Fluoxetine can be decreased when combined with Amlodipine.',
 416: 'MODERATE,The risk or severity of QTc prolongation can be increased when Fluoxetine is combined with Levofloxacin.',
 12: 'MAJOR,The metabolism of Pantoprazole can be decreased when combined with Fluoxetine',
 541: 'MODERATE,The serum concentration of Metoprolol can be increased when it is combined with Fluoxetine.',
 553: 'MODERATE,The serum concentration of the active metabolites of Clopidogrel can be reduced when Clopidogrel is used in combination with Fluoxetine resulting in a loss in efficacy.',
 415: 'MODERATE,The risk or severity of QTc prolongation can be increased when Fluoxetine is combined with Hydrochlorothiazide.',
 510: 'MODERATE,The risk or severity of serotonin syndrome can be increased when Fluoxetine is combined with Tramadol.',
 219: 'MODERATE,Gabapentin may increase the central nervous system depressant (CNS depressant) activities of Fluoxetine.',
 544: 'MODERATE,The serum concentration of Sertraline can be increased when it is combined with Fluoxetine.',
 509: 'MODERATE,The risk or severity of serotonin syndrome can be increased when Fluoxetine is combined with Escitalopram.',
 161: 'MINOR,The risk or severity of gastrointestinal bleeding can be increased when Escitalopram is combined with Ibuprofen.',
 479: 'MODERATE,The risk or severity of hypoglycemia can be increased when Escitalopram is combined with Metformin.',
 22: 'MAJOR,The risk or severity of QTc prolongation can be increased when Ciprofloxacin is combined with Escitalopram.',
 535: 'MODERATE,The serum concentration of Escitalopram can be increased when it is combined with Omeprazole.',
 419: 'MODERATE,The risk or severity of QTc prolongation can be increased when Losartan is combined with Escitalopram.',
 330: 'MODERATE,The metabolism of Escitalopram can be decreased when combined with Amlodipine.',
 25: 'MAJOR,The risk or severity of QTc prolongation can be increased when Levofloxacin is combined with Escitalopram.',
 331: 'MODERATE,The metabolism of Escitalopram can be decreased when combined with Pantoprazole.',
 540: 'MODERATE,The serum concentration of Metoprolol can be increased when it is combined with Escitalopram.',
 450: 'MODERATE,The risk or severity of bleeding can be increased when Escitalopram is combined with Clopidogrel.',
 484: 'MODERATE,The risk or severity of hyponatremia can be increased when Escitalopram is combined with Hydrochlorothiazide.',
 508: 'MODERATE,The risk or severity of serotonin syndrome can be increased when Escitalopram is combined with Tramadol.',
 436: 'MODERATE,The risk or severity of adverse effects can be increased when Gabapentin is combined with Escitalopram.',
 547: 'MODERATE,The serum concentration of Simvastatin can be increased when it is combined with Fluoxetine.',
 150: 'MINOR,The metabolism of Simvastatin can be decreased when combined with Acetaminophen.',
 287: 'MODERATE,The metabolism of Acetylsalicylic acid can be decreased when combined with Simvastatin.',
 97: 'MINOR,Metformin may increase the hypolipidaemic activities of Simvastatin.',
 383: 'MODERATE,The metabolism of Simvastatin can be decreased when combined with Ciprofloxacin.',
 360: 'MODERATE,The metabolism of Omeprazole can be decreased when combined with Simvastatin.',
 264: 'MODERATE,Simvastatin may decrease the excretion rate of Atorvastatin which could result in a higher serum level.',
 265: 'MODERATE,Simvastatin may decrease the excretion rate of Losartan which could result in a higher serum level.',
 545: 'MODERATE,The serum concentration of Simvastatin can be increased when it is combined with Amlodipine.',
 135: 'MINOR,The excretion of Simvastatin can be decreased when combined with Pantoprazole.',
 384: 'MODERATE,The metabolism of Simvastatin can be decreased when combined with Metoprolol.',
 18: 'MAJOR,The metabolism of Simvastatin can be decreased when combined with Clopidogrel.',
 396: 'MODERATE,The metabolism of Tramadol can be increased when combined with Simvastatin.',
 382: 'MODERATE,The metabolism of Sertraline can be decreased when combined with Simvastatin.',
 546: 'MODERATE,The serum concentration of Simvastatin can be increased when it is combined with Escitalopram.',
 304: 'MODERATE,The metabolism of Atorvastatin can be decreased when combined with Ibuprofen.',
 96: 'MINOR,Metformin may increase the hypolipidaemic activities of Atorvastatin.',
 299: 'MODERATE,The metabolism of Atorvastatin can be decreased when combined with Ciprofloxacin.',
 310: 'MODERATE,The metabolism of Atorvastatin can be decreased when combined with Omeprazole.',
 308: 'MODERATE,The metabolism of Atorvastatin can be decreased when combined with Losartan.',
 133: 'MINOR,The excretion of Atorvastatin can be decreased when combined with Pantoprazole.',
 1: 'MAJOR,The metabolism of Atorvastatin can be decreased when combined with Clopidogrel.',
 477: 'MODERATE,The risk or severity of hypoglycemia can be increased when Amlodipine is combined with Metformin.',
 571: 'MODERATE,The therapeutic efficacy of Metformin can be increased when used in combination with Levofloxacin.',
 119: 'MINOR,Pantoprazole may decrease the excretion rate of Metformin which could result in a higher serum level.',
 572: 'MODERATE,The therapeutic efficacy of Metformin can be increased when used in combination with Metoprolol.',
 539: 'MODERATE,The serum concentration of Metformin can be increased when it is combined with Clopidogrel.',
 188: 'MINOR,The therapeutic efficacy of Metformin can be decreased when used in combination with Hydrochlorothiazide.',
 194: 'MINOR,Tramadol may decrease the excretion rate of Metformin which could result in a higher serum level.',
 186: 'MINOR,The therapeutic efficacy of Levothyroxine can be decreased when used in combination with Fluoxetine.',
 566: 'MODERATE,The therapeutic efficacy of Levothyroxine can be increased when used in combination with Acetylsalicylic acid.',
 347: 'MODERATE,The metabolism of Ibuprofen can be decreased when combined with Levothyroxine.',
 568: 'MODERATE,The therapeutic efficacy of Metformin can be decreased when used in combination with Levothyroxine.',
 213: 'MODERATE,Ciprofloxacin can cause a decrease in the absorption of Levothyroxine resulting in a reduced serum concentration and potentially a decrease in efficacy.',
 254: 'MODERATE,Omeprazole can cause a decrease in the absorption of Levothyroxine resulting in a reduced serum concentration and potentially a decrease in efficacy.',
 307: 'MODERATE,The metabolism of Atorvastatin can be decreased when combined with Levothyroxine.',
 258: 'MODERATE,Pantoprazole can cause a decrease in the absorption of Levothyroxine resulting in a reduced serum concentration and potentially a decrease in efficacy.',
 565: 'MODERATE,The therapeutic efficacy of Levothyroxine can be decreased when used in combination with Metoprolol.',
 187: 'MINOR,The therapeutic efficacy of Levothyroxine can be decreased when used in combination with Sertraline.',
 185: 'MINOR,The therapeutic efficacy of Levothyroxine can be decreased when used in combination with Escitalopram.',
 32: 'MINOR,Acetaminophen may decrease the excretion rate of Lisinopril which could result in a higher serum level.',
 567: 'MODERATE,The therapeutic efficacy of Lisinopril can be decreased when used in combination with Acetylsalicylic acid.',
 498: 'MODERATE,The risk or severity of renal failure, hyperkalemia, and hypertension can be increased when Ibuprofen is combined with Lisinopril.',
 486: 'MODERATE,The risk or severity of lactic acidosis can be increased when Lisinopril is combined with Metformin.',
 474: 'MODERATE,The risk or severity of hyperkalemia can be increased when Lisinopril is combined with Ciprofloxacin.',
 84: 'MINOR,Lisinopril may decrease the excretion rate of Amoxicillin which could result in a higher serum level.',
 504: 'MODERATE,The risk or severity of renal failure, hypotension, and hyperkalemia can be increased when Lisinopril is combined with Losartan.',
 153: 'MINOR,The risk or severity of QTc prolongation can be increased when Losartan is combined with Levofloxacin.',
 118: 'MINOR,Pantoprazole may decrease the excretion rate of Lisinopril which could result in a higher serum level.',
 106: 'MINOR,Metoprolol may increase the hypotensive activities of Lisinopril.',
 193: 'MINOR,Tramadol may decrease the excretion rate of Lisinopril which could result in a higher serum level.',
 291: 'MODERATE,The metabolism of Amlodipine can be decreased when combined with Ciprofloxacin.',
 357: 'MODERATE,The metabolism of Omeprazole can be decreased when combined with Amlodipine.',
 363: 'MODERATE,The metabolism of Pantoprazole can be decreased when combined with Amlodipine.',
 246: 'MODERATE,Metoprolol may increase the arrhythmogenic activities of Amlodipine.',
 562: 'MODERATE,The therapeutic efficacy of Clopidogrel can be decreased when used in combination with Amlodipine.',
 169: 'MINOR,The risk or severity of hyperkalemia can be increased when Losartan is combined with Ciprofloxacin.',
 358: 'MODERATE,The metabolism of Omeprazole can be decreased when combined with Losartan.',
 366: 'MODERATE,The metabolism of Pantoprazole can be decreased when combined with Losartan.',
 319: 'MODERATE,The metabolism of Clopidogrel can be decreased when combined with Losartan.',
 391: 'MODERATE,The metabolism of Tramadol can be decreased when combined with Losartan.',
 525: 'MODERATE,The serum concentration of Citalopram can be increased when it is combined with Fluoxetine.',
 281: 'MODERATE,The metabolism of Acetaminophen can be decreased when combined with Citalopram.',
 465: 'MODERATE,The risk or severity of gastrointestinal bleeding can be increased when Citalopram is combined with Acetylsalicylic acid.',
 160: 'MINOR,The risk or severity of gastrointestinal bleeding can be increased when Citalopram is combined with Ibuprofen.',
 478: 'MODERATE,The risk or severity of hypoglycemia can be increased when Citalopram is combined with Metformin.',
 21: 'MAJOR,The risk or severity of QTc prolongation can be increased when Ciprofloxacin is combined with Citalopram.',
 423: 'MODERATE,The risk or severity of QTc prolongation can be increased when Omeprazole is combined with Citalopram.',
 300: 'MODERATE,The metabolism of Atorvastatin can be decreased when combined with Citalopram.',
 242: 'MODERATE,Losartan may increase the QTc-prolonging activities of Citalopram.',
 205: 'MODERATE,Amlodipine may increase the QTc-prolonging activities of Citalopram.',
 24: 'MAJOR,The risk or severity of QTc prolongation can be increased when Levofloxacin is combined with Citalopram.',
 424: 'MODERATE,The risk or severity of QTc prolongation can be increased when Pantoprazole is combined with Citalopram.',
 314: 'MODERATE,The metabolism of Citalopram can be decreased when combined with Metoprolol.',
 468: 'MODERATE,The risk or severity of hemorrhage can be increased when Citalopram is combined with Clopidogrel.',
 483: 'MODERATE,The risk or severity of hyponatremia can be increased when Citalopram is combined with Hydrochlorothiazide.',
 507: 'MODERATE,The risk or severity of serotonin syndrome can be increased when Citalopram is combined with Tramadol.',
 435: 'MODERATE,The risk or severity of adverse effects can be increased when Gabapentin is combined with Citalopram.',
 526: 'MODERATE,The serum concentration of Citalopram can be increased when it is combined with Sertraline.',
 506: 'MODERATE,The risk or severity of serotonin syndrome can be increased when Citalopram is combined with Escitalopram.',
 549: 'MODERATE,The serum concentration of Venlafaxine can be increased when it is combined with Fluoxetine.',
 284: 'MODERATE,The metabolism of Acetaminophen can be decreased when combined with Venlafaxine.',
 581: 'MODERATE,Venlafaxine may increase the antiplatelet activities of Acetylsalicylic acid.',
 81: 'MINOR,Ibuprofen may decrease the excretion rate of Venlafaxine which could result in a higher serum level.',
 482: 'MODERATE,The risk or severity of hypoglycemia can be increased when Venlafaxine is combined with Metformin.',
 397: 'MODERATE,The metabolism of Venlafaxine can be decreased when combined with Ciprofloxacin.',
 197: 'MINOR,Venlafaxine may decrease the excretion rate of Levofloxacin which could result in a higher serum level.',
 122: 'MINOR,Pantoprazole may decrease the excretion rate of Venlafaxine which could result in a higher serum level.',
 174: 'MINOR,The serum concentration of Metoprolol can be increased when it is combined with Venlafaxine.',
 159: 'MINOR,The risk or severity of bleeding can be increased when Clopidogrel is combined with Venlafaxine.',
 235: 'MODERATE,Hydrochlorothiazide may increase the excretion rate of Venlafaxine which could result in a lower serum level and potentially a reduction in efficacy.',
 514: 'MODERATE,The risk or severity of serotonin syndrome can be increased when Venlafaxine is combined with Tramadol.',
 445: 'MODERATE,The risk or severity of adverse effects can be increased when Venlafaxine is combined with Gabapentin.',
 172: 'MINOR,The risk or severity of serotonin syndrome can be increased when Sertraline is combined with Venlafaxine.',
 513: 'MODERATE,The risk or severity of serotonin syndrome can be increased when Venlafaxine is combined with Escitalopram.',
 10: 'MAJOR,The metabolism of Omeprazole can be decreased when combined with Fluoxetine.',
 359: 'MODERATE,The metabolism of Omeprazole can be decreased when combined with Pantoprazole.',
 555: 'MODERATE,The serum concentration of the active metabolites of Clopidogrel can be reduced when Clopidogrel is used in combination with Omeprazole resulting in a loss in efficacy.',
 5: 'MAJOR,The metabolism of Esomeprazole can be decreased when combined with Fluoxetine.',
 334: 'MODERATE,The metabolism of Esomeprazole can be decreased when combined with Ciprofloxacin.',
 336: 'MODERATE,The metabolism of Esomeprazole can be decreased when combined with Omeprazole.',
 335: 'MODERATE,The metabolism of Esomeprazole can be decreased when combined with Losartan.',
 333: 'MODERATE,The metabolism of Esomeprazole can be decreased when combined with Amlodipine.',
 337: 'MODERATE,The metabolism of Esomeprazole can be decreased when combined with Pantoprazole.',
 552: 'MODERATE,The serum concentration of the active metabolites of Clopidogrel can be reduced when Clopidogrel is used in combination with Esomeprazole resulting in a loss in efficacy.',
 273: 'MODERATE,The excretion of Hydrochlorothiazide can be decreased when combined with Esomeprazole.',
 374: 'MODERATE,The metabolism of Sertraline can be decreased when combined with Esomeprazole.',
 534: 'MODERATE,The serum concentration of Escitalopram can be increased when it is combined with Esomeprazole.',
 7: 'MAJOR,The metabolism of Fluoxetine can be decreased when combined with Lansoprazole.',
 136: 'MINOR,The metabolism of Acetaminophen can be decreased when combined with Lansoprazole.',
 138: 'MINOR,The metabolism of Acetylsalicylic acid can be decreased when combined with Lansoprazole.',
 346: 'MODERATE,The metabolism of Ibuprofen can be decreased when combined with Lansoprazole.',
 351: 'MODERATE,The metabolism of Lansoprazole can be decreased when combined with Ciprofloxacin.',
 11: 'MAJOR,The metabolism of Omeprazole can be decreased when combined with Lansoprazole.',
 306: 'MODERATE,The metabolism of Atorvastatin can be decreased when combined with Lansoprazole.',
 352: 'MODERATE,The metabolism of Lansoprazole can be decreased when combined with Losartan.',
 350: 'MODERATE,The metabolism of Lansoprazole can be decreased when combined with Amlodipine.',
 14: 'MAJOR,The metabolism of Pantoprazole can be decreased when combined with Lansoprazole.',
 149: 'MINOR,The metabolism of Metoprolol can be decreased when combined with Lansoprazole.',
 554: 'MODERATE,The serum concentration of the active metabolites of Clopidogrel can be reduced when Clopidogrel is used in combination with Lansoprazole resulting in a loss in efficacy.',
 275: 'MODERATE,The excretion of Hydrochlorothiazide can be decreased when combined with Lansoprazole.',
 390: 'MODERATE,The metabolism of Tramadol can be decreased when combined with Lansoprazole.',
 17: 'MAJOR,The metabolism of Sertraline can be decreased when combined with Lansoprazole.',
 4: 'MAJOR,The metabolism of Escitalopram can be decreased when combined with Lansoprazole.',
 13: 'MAJOR,The metabolism of Pantoprazole can be decreased when combined with Fluoxetine.',
 364: 'MODERATE,The metabolism of Pantoprazole can be decreased when combined with Ciprofloxacin.',
 117: 'MINOR,Pantoprazole may decrease the excretion rate of Levofloxacin which could result in a higher serum level.',
 120: 'MINOR,Pantoprazole may decrease the excretion rate of Metoprolol which could result in a higher serum level.',
 180: 'MINOR,The serum concentration of the active metabolites of Clopidogrel can be reduced when Clopidogrel is used in combination with Pantoprazole resulting in a loss in efficacy.',
 276: 'MODERATE,The excretion of Hydrochlorothiazide can be decreased when combined with Pantoprazole.',
 195: 'MINOR,Tramadol may decrease the excretion rate of Pantoprazole which could result in a higher serum level.',
 379: 'MODERATE,The metabolism of Sertraline can be decreased when combined with Pantoprazole.',
 16: 'MAJOR,The metabolism of Rabeprazole can be decreased when combined with Fluoxetine.',
 33: 'MINOR,Acetaminophen may decrease the excretion rate of Rabeprazole which could result in a higher serum level.',
 42: 'MINOR,Acetylsalicylic acid may decrease the excretion rate of Rabeprazole which could result in a higher serum level.',
 78: 'MINOR,Ibuprofen may decrease the excretion rate of Rabeprazole which could result in a higher serum level.',
 94: 'MINOR,Metformin may decrease the excretion rate of Rabeprazole which could result in a higher serum level.',
 59: 'MINOR,Ciprofloxacin may decrease the excretion rate of Rabeprazole which could result in a higher serum level.',
 50: 'MINOR,Amoxicillin may decrease the excretion rate of Rabeprazole which could result in a higher serum level.',
 369: 'MODERATE,The metabolism of Rabeprazole can be decreased when combined with Omeprazole.',
 311: 'MODERATE,The metabolism of Atorvastatin can be decreased when combined with Rabeprazole.',
 368: 'MODERATE,The metabolism of Rabeprazole can be decreased when combined with Amlodipine.',
 125: 'MINOR,Rabeprazole may decrease the excretion rate of Levofloxacin which could result in a higher serum level.',
 370: 'MODERATE,The metabolism of Rabeprazole can be decreased when combined with Pantoprazole.',
 104: 'MINOR,Metoprolol may decrease the excretion rate of Rabeprazole which could result in a higher serum level.',
 556: 'MODERATE,The serum concentration of the active metabolites of Clopidogrel can be reduced when Clopidogrel is used in combination with Rabeprazole resulting in a loss in efficacy.',
 232: 'MODERATE,Hydrochlorothiazide may increase the excretion rate of Rabeprazole which could result in a lower serum level and potentially a reduction in efficacy.',
 394: 'MODERATE,The metabolism of Tramadol can be decreased when combined with Rabeprazole.',
 381: 'MODERATE,The metabolism of Sertraline can be decreased when combined with Rabeprazole.',
 332: 'MODERATE,The metabolism of Escitalopram can be decreased when combined with Rabeprazole.',
 99: 'MINOR,Metoprolol may decrease the excretion rate of Ciprofloxacin which could result in a higher serum level.',
 98: 'MINOR,Metoprolol may decrease the excretion rate of Amoxicillin which could result in a higher serum level.',
 249: 'MODERATE,Metoprolol may increase the arrhythmogenic activities of Losartan.',
 103: 'MINOR,Metoprolol may decrease the excretion rate of Levofloxacin which could result in a higher serum level.',
 522: 'MODERATE,The serum concentration of Carvedilol can be increased when it is combined with Fluoxetine.',
 212: 'MODERATE,Carvedilol may increase the hepatotoxic activities of Acetaminophen.',
 199: 'MODERATE,Acetylsalicylic acid may decrease the antihypertensive activities of Carvedilol.',
 237: 'MODERATE,Ibuprofen may decrease the antihypertensive activities of Carvedilol.',
 569: 'MODERATE,The therapeutic efficacy of Metformin can be increased when used in combination with Carvedilol.',
 2: 'MAJOR,The metabolism of Carvedilol can be decreased when combined with Ciprofloxacin.',
 144: 'MINOR,The metabolism of Carvedilol can be decreased when combined with Omeprazole.',
 243: 'MODERATE,Losartan may increase the arrhythmogenic activities of Carvedilol.',
 206: 'MODERATE,Amlodipine may increase the arrhythmogenic activities of Carvedilol.',
 248: 'MODERATE,Metoprolol may increase the arrhythmogenic activities of Carvedilol.',
 563: 'MODERATE,The therapeutic efficacy of Clopidogrel can be decreased when used in combination with Carvedilol.',
 145: 'MINOR,The metabolism of Carvedilol can be decreased when combined with Tramadol.',
 523: 'MODERATE,The serum concentration of Carvedilol can be increased when it is combined with Sertraline.',
 521: 'MODERATE,The serum concentration of Carvedilol can be increased when it is combined with Escitalopram.',
 519: 'MODERATE,The serum concentration of Atenolol can be increased when it is combined with Fluoxetine.',
 140: 'MINOR,The metabolism of Atenolol can be decreased when combined with Acetaminophen.',
 198: 'MODERATE,Acetylsalicylic acid may decrease the antihypertensive activities of Atenolol.',
 236: 'MODERATE,Ibuprofen may decrease the antihypertensive activities of Atenolol.',
 538: 'MODERATE,The serum concentration of Metformin can be increased when it is combined with Atenolol.',
 209: 'MODERATE,Atenolol may decrease the excretion rate of Atorvastatin which could result in a higher serum level.',
 211: 'MODERATE,Atenolol may increase the arrhythmogenic activities of Losartan.',
 210: 'MODERATE,Atenolol may increase the arrhythmogenic activities of Amlodipine.',
 247: 'MODERATE,Metoprolol may increase the arrhythmogenic activities of Atenolol.',
 560: 'MODERATE,The therapeutic efficacy of Atenolol can be increased when used in combination with Hydrochlorothiazide.',
 141: 'MINOR,The metabolism of Atenolol can be decreased when combined with Tramadol.',
 520: 'MODERATE,The serum concentration of Atenolol can be increased when it is combined with Sertraline.',
 518: 'MODERATE,The serum concentration of Atenolol can be increased when it is combined with Escitalopram.',
 543: 'MODERATE,The serum concentration of Propranolol can be increased when it is combined with Fluoxetine.',
 367: 'MODERATE,The metabolism of Propranolol can be decreased when combined with Acetaminophen.',
 175: 'MINOR,The serum concentration of Propranolol can be decreased when it is combined with Acetylsalicylic acid.',
 239: 'MODERATE,Ibuprofen may decrease the antihypertensive activities of Propranolol.',
 573: 'MODERATE,The therapeutic efficacy of Metformin can be increased when used in combination with Propranolol.',
 15: 'MAJOR,The metabolism of Propranolol can be decreased when combined with Ciprofloxacin.',
 123: 'MINOR,Propranolol may decrease the excretion rate of Amoxicillin which could result in a higher serum level.',
 177: 'MINOR,The serum concentration of Propranolol can be increased when it is combined with Omeprazole.',
 143: 'MINOR,The metabolism of Atorvastatin can be decreased when combined with Propranolol.',
 176: 'MINOR,The serum concentration of Propranolol can be increased when it is combined with Losartan.',
 207: 'MODERATE,Amlodipine may increase the arrhythmogenic activities of Propranolol.',
 124: 'MINOR,Propranolol may decrease the excretion rate of Levofloxacin which could result in a higher serum level.',
 178: 'MINOR,The serum concentration of Propranolol can be increased when it is combined with Pantoprazole.',
 250: 'MODERATE,Metoprolol may increase the arrhythmogenic activities of Propranolol.',
 321: 'MODERATE,The metabolism of Clopidogrel can be decreased when combined with Propranolol.',
 393: 'MODERATE,The metabolism of Tramadol can be decreased when combined with Propranolol.',
 179: 'MINOR,The serum concentration of Propranolol can be increased when it is combined with Sertraline.',
 542: 'MODERATE,The serum concentration of Propranolol can be increased when it is combined with Escitalopram.',
 225: 'MODERATE,Hydrochlorothiazide may increase the excretion rate of Ciprofloxacin which could result in a lower serum level and potentially a reduction in efficacy.',
 224: 'MODERATE,Hydrochlorothiazide may increase the excretion rate of Amoxicillin which could result in a lower serum level and potentially a reduction in efficacy.',
 230: 'MODERATE,Hydrochlorothiazide may increase the excretion rate of Levofloxacin which could result in a lower serum level and potentially a reduction in efficacy.',
 256: 'MODERATE,Organic anion transporter 3 (OAT3) is responsible for the excretion of a wide variety of drugs, toxins, and metabolites in the kidney, liver, and other tissues 3. Inhibitors of this transporter attenuates the drug efflux, leading to increased serum concentrations of OAT3 substrates. Co-administration of OAT3 inhibitors with OAT3 substrates, and resulting elevating systemic exposure to those substrates, may alter the clinical efficacy of drug therapy and increase the risk for developing drug-related adverse reactions.',
 234: 'MODERATE,Hydrochlorothiazide may increase the excretion rate of Tramadol which could result in a lower serum level and potentially a reduction in efficacy.',
 558: 'MODERATE,The subject drug induces diuresis1,2, which can theoretically increase the excretion rate of the affected drug, which is eliminated by the kidneys. Additionally, it could affect renal tubular reabsorption of certain drugs. Exposure to the affected drug can be markedly reduced, leading to subtherapeutic drug levels that are unlikely to elicit an adequate clinical response.',
 561: 'MODERATE,The therapeutic efficacy of Benazepril can be decreased when used in combination with Acetylsalicylic acid.',
 497: 'MODERATE,The risk or severity of renal failure, hyperkalemia, and hypertension can be increased when Ibuprofen is combined with Benazepril.',
 473: 'MODERATE,The risk or severity of hyperkalemia can be increased when Benazepril is combined with Ciprofloxacin.',
 503: 'MODERATE,The risk or severity of renal failure, hypotension, and hyperkalemia can be increased when Benazepril is combined with Losartan.',
 69: 'MINOR,Hydrochlorothiazide may increase the hypotensive activities of Benazepril.',
 502: 'MODERATE,The risk or severity of renal failure, hyperkalemia, and hypertension can be increased when Valsartan is combined with Ibuprofen.',
 362: 'MODERATE,The metabolism of Omeprazole can be decreased when combined with Valsartan.',
 134: 'MINOR,The excretion of Atorvastatin can be decreased when combined with Valsartan.',
 505: 'MODERATE,The risk or severity of renal failure, hypotension, and hyperkalemia can be increased when Valsartan is combined with Losartan.',
 196: 'MINOR,Valsartan may increase the hypotensive activities of Metoprolol.',
 322: 'MODERATE,The metabolism of Clopidogrel can be decreased when combined with Valsartan.',
 267: 'MODERATE,Spironolactone may increase the excretion rate of Acetaminophen which could result in a lower serum level and potentially a reduction in efficacy.',
 575: 'MODERATE,The therapeutic efficacy of Spironolactone can be decreased when used in combination with Acetylsalicylic acid.',
 576: 'MODERATE,The therapeutic efficacy of Spironolactone can be decreased when used in combination with Ibuprofen.',
 270: 'MODERATE,Spironolactone may increase the excretion rate of Metformin which could result in a lower serum level and potentially a reduction in efficacy.',
 266: 'MODERATE,Spironolactone may increase the arrhythmogenic activities of Ciprofloxacin.',
 268: 'MODERATE,Spironolactone may increase the excretion rate of Amoxicillin which could result in a lower serum level and potentially a reduction in efficacy.',
 361: 'MODERATE,The metabolism of Omeprazole can be decreased when combined with Spironolactone.',
 312: 'MODERATE,The metabolism of Atorvastatin can be decreased when combined with Spironolactone.',
 475: 'MODERATE,The risk or severity of hyperkalemia can be increased when Spironolactone is combined with Losartan.',
 155: 'MINOR,The risk or severity of adverse effects can be increased when Amlodipine is combined with Spironolactone.',
 269: 'MODERATE,Spironolactone may increase the excretion rate of Levofloxacin which could result in a lower serum level and potentially a reduction in efficacy.',
 272: 'MODERATE,Spironolactone may increase the excretion rate of Pantoprazole which could result in a lower serum level and potentially a reduction in efficacy.',
 271: 'MODERATE,Spironolactone may increase the excretion rate of Metoprolol which could result in a lower serum level and potentially a reduction in efficacy.',
 496: 'MODERATE,The risk or severity of orthostatic hypotension can be increased when Tramadol is combined with Spironolactone.',
 472: 'MODERATE,The risk or severity of hemorrhage can be increased when Fluoxetine is combined with Warfarin.',
 425: 'MODERATE,The risk or severity of adverse effects can be increased when Acetaminophen is combined with Warfarin.',
 204: 'MODERATE,Acetylsalicylic acid may increase the anticoagulant activities of Warfarin.',
 241: 'MODERATE,Ibuprofen may decrease the excretion rate of Warfarin which could result in a higher serum level.',
 244: 'MODERATE,Metformin may decrease the excretion rate of Warfarin which could result in a higher serum level.',
 550: 'MODERATE,The serum concentration of Warfarin can be increased when it is combined with Ciprofloxacin.',
 208: 'MODERATE,Amoxicillin may decrease the excretion rate of Warfarin which could result in a higher serum level.',
 398: 'MODERATE,The metabolism of Warfarin can be decreased when combined with Omeprazole.',
 151: 'MINOR,The metabolism of Warfarin can be decreased when combined with Atorvastatin.',
 551: 'MODERATE,The serum concentration of Warfarin can be increased when it is combined with Losartan.',
 19: 'MAJOR,The metabolism of Warfarin can be decreased when combined with Amlodipine.',
 577: 'MODERATE,The therapeutic efficacy of Warfarin can be increased when used in combination with Levofloxacin.',
 262: 'MODERATE,Pantoprazole may decrease the excretion rate of Warfarin which could result in a higher serum level.',
 245: 'MODERATE,Metoprolol may decrease the excretion rate of Warfarin which could result in a higher serum level.',
 448: 'MODERATE,The risk or severity of bleeding can be increased when Clopidogrel is combined with Warfarin.',
 221: 'MODERATE,Hydrochlorothiazide may decrease the excretion rate of Warfarin which could result in a higher serum level.',
 578: 'MODERATE,The therapeutic efficacy of Warfarin can be increased when used in combination with Tramadol.',
 463: 'MODERATE,The risk or severity of bleeding can be increased when Sertraline is combined with Warfarin.',
 453: 'MODERATE,The risk or severity of bleeding can be increased when Escitalopram is combined with Warfarin.',
 3: 'MAJOR,The metabolism of Clopidogrel can be decreased when combined with Ciprofloxacin.',
 579: 'MODERATE,Tramadol can cause a decrease in the absorption of Clopidogrel resulting in a reduced serum concentration and potentially a decrease in efficacy.',
 557: 'MODERATE,The serum concentration of the active metabolites of Clopidogrel can be reduced when Clopidogrel is used in combination with Sertraline resulting in a loss in efficacy.',
 410: 'MODERATE,The risk or severity of QTc prolongation can be increased when Ciprofloxacin is combined with Levofloxacin.',
 192: 'MINOR,Tramadol may decrease the excretion rate of Levofloxacin which could result in a higher serum level.',
 570: 'MODERATE,The therapeutic efficacy of Metformin can be increased when used in combination with Ciprofloxacin.',
 524: 'MODERATE,The serum concentration of Ciprofloxacin can be increased when it is combined with Amoxicillin.',
 386: 'MODERATE,The metabolism of Tramadol can be decreased when combined with Ciprofloxacin.',
 418: 'MODERATE,The risk or severity of QTc prolongation can be increased when Fluoxetine is combined with Metronidazole.',
 354: 'MODERATE,The metabolism of Metronidazole can be decreased when combined with Acetaminophen.',
 286: 'MODERATE,The metabolism of Acetylsalicylic acid can be decreased when combined with Metronidazole.',
 348: 'MODERATE,The metabolism of Ibuprofen can be decreased when combined with Metronidazole.',
 355: 'MODERATE,The metabolism of Metronidazole can be decreased when combined with Ciprofloxacin.',
 309: 'MODERATE,The metabolism of Atorvastatin can be decreased when combined with Metronidazole.',
 420: 'MODERATE,The risk or severity of QTc prolongation can be increased when Losartan is combined with Metronidazole.',
 154: 'MINOR,The risk or severity of QTc prolongation can be increased when Metronidazole is combined with Levofloxacin.',
 320: 'MODERATE,The metabolism of Clopidogrel can be decreased when combined with Metronidazole.',
 422: 'MODERATE,The risk or severity of QTc prolongation can be increased when Metronidazole is combined with Hydrochlorothiazide.',
 392: 'MODERATE,The metabolism of Tramadol can be decreased when combined with Metronidazole.',
 564: 'MODERATE,The therapeutic efficacy of Gabapentin can be decreased when used in combination with Metronidazole.',
 377: 'MODERATE,The metabolism of Sertraline can be decreased when combined with Metronidazole.',
 421: 'MODERATE,The risk or severity of QTc prolongation can be increased when Metronidazole is combined with Escitalopram.',
 34: 'MINOR,Acetaminophen may decrease the excretion rate of Tetracycline which could result in a higher serum level.',
 278: 'MODERATE,The excretion of Tetracycline can be decreased when combined with Acetylsalicylic acid.',
 279: 'MODERATE,The excretion of Tetracycline can be decreased when combined with Ibuprofen.',
 95: 'MINOR,Metformin may decrease the excretion rate of Tetracycline which could result in a higher serum level.',
 385: 'MODERATE,The metabolism of Tetracycline can be decreased when combined with Ciprofloxacin.',
 28: 'MAJOR,The therapeutic efficacy of Amoxicillin can be decreased when used in combination with Tetracycline.',
 313: 'MODERATE,The metabolism of Atorvastatin can be decreased when combined with Tetracycline.',
 132: 'MINOR,Tetracycline may decrease the excretion rate of Levofloxacin which could result in a higher serum level.',
 280: 'MODERATE,The excretion of Tetracycline can be decreased when combined with Pantoprazole.',
 105: 'MINOR,Metoprolol may decrease the excretion rate of Tetracycline which could result in a higher serum level.',
 277: 'MODERATE,The excretion of Hydrochlorothiazide can be decreased when combined with Tetracycline.',
 395: 'MODERATE,The metabolism of Tramadol can be decreased when combined with Tetracycline.',
 62: 'MINOR,Doxycycline may decrease the excretion rate of Acetaminophen which could result in a higher serum level.',
 38: 'MINOR,Acetylsalicylic acid may decrease the excretion rate of Doxycycline which could result in a higher serum level.',
 74: 'MINOR,Ibuprofen may decrease the excretion rate of Doxycycline which could result in a higher serum level.',
 65: 'MINOR,Doxycycline may decrease the excretion rate of Metformin which could result in a higher serum level.',
 63: 'MINOR,Doxycycline may decrease the excretion rate of Ciprofloxacin which could result in a higher serum level.',
 27: 'MAJOR,The therapeutic efficacy of Amoxicillin can be decreased when used in combination with Doxycycline.',
 253: 'MODERATE,Omeprazole can cause a decrease in the absorption of Doxycycline resulting in a reduced serum concentration and potentially a decrease in efficacy.',
 64: 'MINOR,Doxycycline may decrease the excretion rate of Levofloxacin which could result in a higher serum level.',
 257: 'MODERATE,Pantoprazole can cause a decrease in the absorption of Doxycycline resulting in a reduced serum concentration and potentially a decrease in efficacy.',
 66: 'MINOR,Doxycycline may decrease the excretion rate of Metoprolol which could result in a higher serum level.',
 228: 'MODERATE,Hydrochlorothiazide may increase the excretion rate of Doxycycline which could result in a lower serum level and potentially a reduction in efficacy.',
 191: 'MINOR,Tramadol may decrease the excretion rate of Doxycycline which could result in a higher serum level.',
 316: 'MODERATE,The metabolism of Clindamycin can be increased when combined with Acetaminophen.',
 315: 'MODERATE,The metabolism of Clindamycin can be decreased when combined with Ciprofloxacin.',
 430: 'MODERATE,The risk or severity of adverse effects can be increased when Clindamycin is combined with Atorvastatin.',
 146: 'MINOR,The metabolism of Clindamycin can be decreased when combined with Clopidogrel.',
 414: 'MODERATE,The risk or severity of QTc prolongation can be increased when Fluoxetine is combined with Erythromycin.',
 282: 'MODERATE,The metabolism of Acetaminophen can be decreased when combined with Erythromycin.',
 344: 'MODERATE,The metabolism of Ibuprofen can be decreased when combined with Erythromycin.',
 411: 'MODERATE,The risk or severity of QTc prolongation can be increased when Erythromycin is combined with Ciprofloxacin.',
 26: 'MAJOR,The serum concentration of Atorvastatin can be increased when it is combined with Erythromycin.',
 216: 'MODERATE,Erythromycin may decrease the excretion rate of Losartan which could result in a higher serum level.',
 412: 'MODERATE,The risk or severity of QTc prolongation can be increased when Erythromycin is combined with Levofloxacin.',
 365: 'MODERATE,The metabolism of Pantoprazole can be decreased when combined with Erythromycin.',
 318: 'MODERATE,The metabolism of Clopidogrel can be decreased when combined with Erythromycin.',
 152: 'MINOR,The risk or severity of QTc prolongation can be increased when Hydrochlorothiazide is combined with Erythromycin.',
 389: 'MODERATE,The metabolism of Tramadol can be decreased when combined with Erythromycin.',
 373: 'MODERATE,The metabolism of Sertraline can be decreased when combined with Erythromycin.',
 23: 'MAJOR,The risk or severity of QTc prolongation can be increased when Erythromycin is combined with Escitalopram.',
 218: 'MODERATE,Fluoxetine may increase the central nervous system depressant (CNS depressant) activities of Zolpidem.',
 404: 'MODERATE,The metabolism of Zolpidem can be increased when combined with Acetaminophen.',
 139: 'MINOR,The metabolism of Acetylsalicylic acid can be decreased when combined with Zolpidem.',
 148: 'MINOR,The metabolism of Ibuprofen can be decreased when combined with Zolpidem.',
 20: 'MAJOR,The metabolism of Zolpidem can be decreased when combined with Ciprofloxacin.',
 402: 'MODERATE,The metabolism of Zolpidem can be decreased when combined with Omeprazole.',
 400: 'MODERATE,The metabolism of Zolpidem can be decreased when combined with Losartan.',
 399: 'MODERATE,The metabolism of Zolpidem can be decreased when combined with Amlodipine.',
 403: 'MODERATE,The metabolism of Zolpidem can be decreased when combined with Pantoprazole.',
 401: 'MODERATE,The metabolism of Zolpidem can be decreased when combined with Metoprolol.',
 323: 'MODERATE,The metabolism of Clopidogrel can be decreased when combined with Zolpidem.',
 580: 'MODERATE,Tramadol may increase the central nervous system depressant (CNS depressant) activities of Zolpidem.',
 220: 'MODERATE,Gabapentin may increase the central nervous system depressant (CNS depressant) activities of Zolpidem.',
 263: 'MODERATE,Sertraline may increase the central nervous system depressant (CNS depressant) activities of Zolpidem.',
 217: 'MODERATE,Escitalopram may increase the central nervous system depressant (CNS depressant) activities of Zolpidem.',
 406: 'MODERATE,The risk or severity of CNS depression can be increased when Fluoxetine is combined with Eszopiclone.',
 536: 'MODERATE,The serum concentration of Eszopiclone can be decreased when it is combined with Acetaminophen.',
 39: 'MINOR,Acetylsalicylic acid may decrease the excretion rate of Eszopiclone which could result in a higher serum level.',
 345: 'MODERATE,The metabolism of Ibuprofen can be decreased when combined with Eszopiclone.',
 93: 'MINOR,Metformin may decrease the excretion rate of Eszopiclone which could result in a higher serum level.',
 338: 'MODERATE,The metabolism of Eszopiclone can be decreased when combined with Ciprofloxacin.',
 67: 'MINOR,Eszopiclone may decrease the excretion rate of Amoxicillin which could result in a higher serum level.',
 340: 'MODERATE,The metabolism of Eszopiclone can be decreased when combined with Omeprazole.',
 303: 'MODERATE,The metabolism of Atorvastatin can be decreased when combined with Eszopiclone.',
 339: 'MODERATE,The metabolism of Eszopiclone can be decreased when combined with Losartan.',
 68: 'MINOR,Eszopiclone may decrease the excretion rate of Levofloxacin which could result in a higher serum level.',
 116: 'MINOR,Pantoprazole may decrease the excretion rate of Eszopiclone which could result in a higher serum level.',
 102: 'MINOR,Metoprolol may decrease the excretion rate of Eszopiclone which could result in a higher serum level.',
 6: 'MAJOR,The metabolism of Eszopiclone can be decreased when combined with Clopidogrel.',
 229: 'MODERATE,Hydrochlorothiazide may increase the excretion rate of Eszopiclone which could result in a lower serum level and potentially a reduction in efficacy.',
 548: 'MODERATE,The serum concentration of Temazepam can be increased when it is combined with Fluoxetine.',
 126: 'MINOR,Temazepam may decrease the excretion rate of Acetaminophen which could result in a higher serum level.',
 43: 'MINOR,Acetylsalicylic acid may decrease the excretion rate of Temazepam which could result in a higher serum level.',
 79: 'MINOR,Ibuprofen may decrease the excretion rate of Temazepam which could result in a higher serum level.',
 130: 'MINOR,Temazepam may decrease the excretion rate of Metformin which could result in a higher serum level.',
 128: 'MINOR,Temazepam may decrease the excretion rate of Ciprofloxacin which could result in a higher serum level.',
 127: 'MINOR,Temazepam may decrease the excretion rate of Amoxicillin which could result in a higher serum level.',
 129: 'MINOR,Temazepam may decrease the excretion rate of Levofloxacin which could result in a higher serum level.',
 121: 'MINOR,Pantoprazole may decrease the excretion rate of Temazepam which could result in a higher serum level.',
 131: 'MINOR,Temazepam may decrease the excretion rate of Metoprolol which could result in a higher serum level.',
 233: 'MODERATE,Hydrochlorothiazide may increase the excretion rate of Temazepam which could result in a lower serum level and potentially a reduction in efficacy.',
 409: 'MODERATE,The risk or severity of CNS depression can be increased when Temazepam is combined with Tramadol.',
 444: 'MODERATE,The risk or severity of adverse effects can be increased when Temazepam is combined with Gabapentin.',
 443: 'MODERATE,The risk or severity of adverse effects can be increased when Temazepam is combined with Escitalopram.',
 426: 'MODERATE,The risk or severity of adverse effects can be increased when Acetylsalicylic acid is combined with Alendronic acid.',
 438: 'MODERATE,The risk or severity of adverse effects can be increased when Ibuprofen is combined with Alendronic acid.',
 488: 'MODERATE,The risk or severity of myopathy, rhabdomyolysis, and myoglobinuria can be increased when Ciprofloxacin is combined with Alendronic acid.',
 181: 'MINOR,The therapeutic efficacy of Alendronic acid can be decreased when used in combination with Omeprazole.',
 487: 'MODERATE,The risk or severity of myopathy, rhabdomyolysis, and myoglobinuria can be increased when Alendronic acid is combined with Atorvastatin.',
 182: 'MINOR,The therapeutic efficacy of Alendronic acid can be decreased when used in combination with Pantoprazole.',
 491: 'MODERATE,The risk or severity of nephrotoxicity and hypocalcemia can be increased when Hydrochlorothiazide is combined with Alendronic acid.',
 464: 'MODERATE,The risk or severity of gastrointestinal bleeding can be increased when Acetylsalicylic acid is combined with Risedronic acid.',
 489: 'MODERATE,The risk or severity of myopathy, rhabdomyolysis, and myoglobinuria can be increased when Ciprofloxacin is combined with Risedronic acid.',
 255: 'MODERATE,Omeprazole can cause an increase in the absorption of Risedronic acid resulting in an increased serum concentration and potentially a worsening of adverse effects.',
 490: 'MODERATE,The risk or severity of myopathy, rhabdomyolysis, and myoglobinuria can be increased when Risedronic acid is combined with Atorvastatin.',
 259: 'MODERATE,Pantoprazole can cause an increase in the absorption of Risedronic acid resulting in an increased serum concentration and potentially a worsening of adverse effects.',
 492: 'MODERATE,The risk or severity of nephrotoxicity and hypocalcemia can be increased when Hydrochlorothiazide is combined with Risedronic acid.',
 471: 'MODERATE,The risk or severity of hemorrhage can be increased when Fluoxetine is combined with Heparin.',
 203: 'MODERATE,Acetylsalicylic acid may increase the anticoagulant activities of Heparin.',
 168: 'MINOR,The risk or severity of hyperkalemia can be increased when Ibuprofen is combined with Heparin.',
 167: 'MINOR,The risk or severity of hyperkalemia can be increased when Heparin is combined with Losartan.',
 166: 'MINOR,The risk or severity of hyperkalemia can be increased when Amlodipine is combined with Heparin.',
 170: 'MINOR,The risk or severity of hyperkalemia can be increased when Metoprolol is combined with Heparin.',
 447: 'MODERATE,The risk or severity of bleeding can be increased when Clopidogrel is combined with Heparin.',
 184: 'MINOR,The therapeutic efficacy of Heparin can be decreased when used in combination with Hydrochlorothiazide.',
 462: 'MODERATE,The risk or severity of bleeding can be increased when Sertraline is combined with Heparin.',
 452: 'MODERATE,The risk or severity of bleeding can be increased when Escitalopram is combined with Heparin.',
 469: 'MODERATE,The risk or severity of hemorrhage can be increased when Fluoxetine is combined with Apixaban.',
 427: 'MODERATE,The risk or severity of adverse effects can be increased when Acetylsalicylic acid is combined with Apixaban.',
 446: 'MODERATE,The risk or severity of bleeding and gastrointestinal bleeding can be increased when Ibuprofen is combined with Apixaban.',
 295: 'MODERATE,The metabolism of Apixaban can be decreased when combined with Ciprofloxacin.',
 297: 'MODERATE,The metabolism of Apixaban can be decreased when combined with Omeprazole.',
 294: 'MODERATE,The metabolism of Apixaban can be decreased when combined with Atorvastatin.',
 296: 'MODERATE,The metabolism of Apixaban can be decreased when combined with Losartan.',
 293: 'MODERATE,The metabolism of Apixaban can be decreased when combined with Amlodipine.',
 260: 'MODERATE,Pantoprazole may decrease the excretion rate of Apixaban which could result in a higher serum level.',
 431: 'MODERATE,The risk or severity of adverse effects can be increased when Clopidogrel is combined with Apixaban.',
 183: 'MINOR,The therapeutic efficacy of Apixaban can be decreased when used in combination with Hydrochlorothiazide.',
 460: 'MODERATE,The risk or severity of bleeding can be increased when Sertraline is combined with Apixaban.',
 449: 'MODERATE,The risk or severity of bleeding can be increased when Escitalopram is combined with Apixaban.',
 470: 'MODERATE,The risk or severity of hemorrhage can be increased when Fluoxetine is combined with Dabigatran etexilate.',
 30: 'MINOR,Acetaminophen may decrease the excretion rate of Dabigatran etexilate which could result in a higher serum level.',
 202: 'MODERATE,Acetylsalicylic acid may increase the anticoagulant activities of Dabigatran etexilate.',
 72: 'MINOR,Ibuprofen may decrease the excretion rate of Dabigatran etexilate which could result in a higher serum level.',
 91: 'MINOR,Metformin may decrease the excretion rate of Dabigatran etexilate which could result in a higher serum level.',
 58: 'MINOR,Ciprofloxacin may decrease the excretion rate of Dabigatran etexilate which could result in a higher serum level.',
 49: 'MINOR,Amoxicillin may decrease the excretion rate of Dabigatran etexilate which could result in a higher serum level.',
 112: 'MINOR,Omeprazole can cause a decrease in the absorption of Dabigatran etexilate resulting in a reduced serum concentration and potentially a decrease in efficacy.',
 83: 'MINOR,Levofloxacin may decrease the excretion rate of Dabigatran etexilate which could result in a higher serum level.',
 113: 'MINOR,Pantoprazole can cause a decrease in the absorption of Dabigatran etexilate resulting in a reduced serum concentration and potentially a decrease in efficacy.',
 100: 'MINOR,Metoprolol may decrease the excretion rate of Dabigatran etexilate which could result in a higher serum level.',
 214: 'MODERATE,Clopidogrel may increase the anticoagulant activities of Dabigatran etexilate.',
 226: 'MODERATE,Hydrochlorothiazide may increase the excretion rate of Dabigatran etexilate which could result in a lower serum level and potentially a reduction in efficacy.',
 190: 'MINOR,Tramadol may decrease the excretion rate of Dabigatran etexilate which could result in a higher serum level.',
 461: 'MODERATE,The risk or severity of bleeding can be increased when Sertraline is combined with Dabigatran etexilate.',
 451: 'MODERATE,The risk or severity of bleeding can be increased when Escitalopram is combined with Dabigatran etexilate.',
 530: 'MODERATE,The serum concentration of Doxorubicin can be increased when it is combined with Fluoxetine.',
 527: 'MODERATE,The serum concentration of Doxorubicin can be increased when it is combined with Acetaminophen.',
 156: 'MINOR,The risk or severity of bleeding can be increased when Acetylsalicylic acid is combined with Doxorubicin.',
 528: 'MODERATE,The serum concentration of Doxorubicin can be increased when it is combined with Ciprofloxacin.',
 302: 'MODERATE,The metabolism of Atorvastatin can be decreased when combined with Doxorubicin.',
 531: 'MODERATE,The serum concentration of Doxorubicin can be increased when it is combined with Losartan.',
 261: 'MODERATE,Pantoprazole may decrease the excretion rate of Doxorubicin which could result in a higher serum level.',
 532: 'MODERATE,The serum concentration of Doxorubicin can be increased when it is combined with Metoprolol.',
 158: 'MINOR,The risk or severity of bleeding can be increased when Clopidogrel is combined with Doxorubicin.',
 171: 'MINOR,The risk or severity of neutropenia and thrombocytopenia can be increased when Hydrochlorothiazide is combined with Doxorubicin.',
 388: 'MODERATE,The metabolism of Tramadol can be decreased when combined with Doxorubicin.',
 533: 'MODERATE,The serum concentration of Doxorubicin can be increased when it is combined with Sertraline.',
 529: 'MODERATE,The serum concentration of Doxorubicin can be increased when it is combined with Escitalopram.',
 51: 'MINOR,Carboplatin may decrease the excretion rate of Acetaminophen which could result in a higher serum level.',
 493: 'MODERATE,The risk or severity of nephrotoxicity can be increased when Acetylsalicylic acid is combined with Carboplatin.',
 495: 'MODERATE,The risk or severity of nephrotoxicity can be increased when Carboplatin is combined with Ibuprofen.',
 55: 'MINOR,Carboplatin may decrease the excretion rate of Metformin which could result in a higher serum level.',
 53: 'MINOR,Carboplatin may decrease the excretion rate of Ciprofloxacin which could result in a higher serum level.',
 52: 'MINOR,Carboplatin may decrease the excretion rate of Amoxicillin which could result in a higher serum level.',
 54: 'MINOR,Carboplatin may decrease the excretion rate of Levofloxacin which could result in a higher serum level.',
 57: 'MINOR,Carboplatin may decrease the excretion rate of Pantoprazole which could result in a higher serum level.',
 56: 'MINOR,Carboplatin may decrease the excretion rate of Metoprolol which could result in a higher serum level.',
 157: 'MINOR,The risk or severity of bleeding can be increased when Clopidogrel is combined with Carboplatin.',
 494: 'MODERATE,The risk or severity of nephrotoxicity can be increased when Carboplatin is combined with Hydrochlorothiazide.',
 189: 'MINOR,Tramadol may decrease the excretion rate of Amoxicillin which could result in a higher serum level.',
 407: 'MODERATE,The risk or severity of CNS depression can be increased when Gabapentin is combined with Tramadol.'}
with open(f'model1.pkl', 'rb') as f:
    model = pickle.load(f)
app = flask.Flask(__name__, template_folder='templates')

@app.route('/', methods=['GET', 'POST'])
def main():
    if flask.request.method == 'GET':
       return(flask.render_template('new.html')) 
    if flask.request.method == 'POST':
       Drug_1 = flask.request.form['drug1']
       Drug_2 = flask.request.form['drug2'] 
      # input_variables = pd.DataFrame([[Drug_1,Drug_2]],columns=['Drug_1','Drug_2'],index=['input'])
    #  drugs['input'] = 

       docs_new = Drug_1 + " and " + Drug_2
       docs_new = [docs_new]
       #print( docs_new)
       predicted = model.predict(docs_new)
       results = v[predicted[0]]
       severity = results[0:8]

   
       return flask.render_template('new.html',original_input={'Drugs':docs_new},result=severity,des=results)
if __name__ == '__main__':
   app.run(debug=True)
